### PR TITLE
Updated to latest Agda Commit.

### PR DESCRIPTION
**Pull request by xekoukou**
All tests pass but there are still some problems.

1. I am not sure how to handle the additional information on the type CaseInfo. I have opted to
always match eagerly.
2. the new primitive Word64 cannot be mapped to OCaml because it does not have unsigned Integers.
Moreover , agda returns code that is never called by Main. This made the test RedBlack.agda to fail.
I mapped all the function calls and removed the code that is not used by the main function.
Is this the correct way? 

It would be better if this was done at the treeless level so that the other backends profit from this removal.

3. I am not able to run the benchmarks. I am not a haskell guru. Something is wrong with the cpp preprocessor .

update : Benchmarks are now working.

### CODE REVIEW

**Comment by gallais** [comment]
> the new primitive Word64 cannot be mapped to OCaml because it does not have unsigned Integers.

related: ocaml/ocaml/pull/1201

I don't know what the status of that PR is but the first post mentions 2 libraries which could be used in the meantime:

* https://github.com/ocamllabs/ocaml-integers
* https://github.com/andrenth/ocaml-stdint


> I mapped all the function calls and removed the code that is not used by the main function. Is this the correct way?

I expect this would break separate compilation: even if some code is not directly used by the executable at hand, you'd want the module interface to be kept the same so that the compilation unit can be reused.

Or is agda-ocaml generating one big module at the moment?

**Comment by xekoukou** [comment]
Indeed, it would break separate compilation.

> Or is agda-ocaml generating one big module at the moment?

I do not really know. From the tests, I can see that there is only one module, this is why it works.

**Comment by UlfNorell** [comment]
> I mapped all the function calls and removed the code that is not used by the main function.
Is this the correct way?

> It would be better if this was done at the treeless level so that the other backends profit from this removal.

> Or is agda-ocaml generating one big module at the moment?

The OCaml backend is (as far as I remember) doing whole program compilation, so getting rid of dead code makes sense. The other backends, however, are not, so we can't do the same dead code analysis anyway.

At the moment we do some pruning (`Agda.TypeChecking.DeadCode`), which prunes code for agdai files that's not needed for type checking outside the module.

**Comment by xekoukou** [comment]
As you can see [here](https://github.com/agda/agda-ocaml/blob/master/src/full/Agda/Compiler/Malfunction.hs#L66) , @fredefox et al concat all Definitions and compile them together at the postCompile step.

@gallais I am not so much interested in unsigned integers, just not make them crash the program.

**Comment by fredefox** [comment]
Hi @xekoukou 

I've made some changes to this PR but I don't have push access to your repo so I've placed them on [this branch](https://github.com/agda/agda-ocaml/tree/xekoukou) in stead. If you can merge them in to your branch and update this PR that would be great.

With these changes I can successfully run the tests on my machine (except the last one, I haven't installed agda-stdlib on my new machine yet) though the benchmarks are still not working. I think perhaps @janmasrovira did some black magic here that I'm not quite sure how is supposed to work. I get this error:

```
/home/fredefox/git/agda/agda-ocaml/benchmark/agda-ocaml/AgdaListGen.hs:7:17: error:
    • Variable not in scope: len :: Int
    • Perhaps you meant ‘lex’ (imported from Prelude)
  |         
7 | theListLength = len
  |                 ^^^
            
/home/fredefox/git/agda/agda-ocaml/benchmark/agda-ocaml/AgdaListGen.hs:36:29: error:
    Variable not in scope: theListDef :: String
   |        
36 |                           , theListDef]
   |                             ^^^^^^^^^^
```

**Comment by xekoukou** [comment]
Try running [this](https://github.com/agda/agda-ocaml/blob/master/benchmark/agda-ocaml/run.sh)  file for the benchmarks.

**Comment by xekoukou** [comment]
Done.

**Comment by fredefox** [comment]
@xekoukou do you want to open another PR for the changes you have on your other branch? I've pushed some changes to it [on this branch](https://github.com/agda/agda-ocaml/tree/xekoukou). The golden tests are still not working for me. IIRC the invocation of agda-ocaml is supposed to generate output on stdout. This is then compared against the contents of the files with the `.golden` suffix. WIth your changes to the CLI the behaviour has changed in an incompatible way. I think it has something to do with the "am-I-main" behaviour you implemented. Perhaps the correct fix it to make the tested agda modules appear to be main modules?

**Comment by xekoukou** [comment]
@fredefox You can merge this pr since the tests pass with this branch. With the ```frontier1``` branch , I have made changes that make the tests fail, so as to be able to perform [agda](https://github.com/agda/agda/tree/master/test/Compiler/simple) 's tests. 

I do not really know much about test frameworks. You could either change the tests so as to look like agda's tests, or we could simply add the tests we want into agda's by forking agda and putting them into the directory. For the moment, I have made some changes into my local agda repository so as to perform tests against agda-ocaml.
(ofcourse, none of the tests pass now, because we haven't implemented pragmas, something I am working right now.)

**Comment by fredefox** [comment]
@xekoukou I've pushed (an empty) backlog to the repo. Could you quickly describe the changes you made?

**Comment by fredefox** [comment]
I've also added a back log with a couply of entries. Could you look at the error call at `Agda.Compiler.Malfunction.EraseDefs.eraseB`?

**Comment by xekoukou** [comment]
Is it even possible to have unnamed bindings? Can you give me an example?

The only example I can think of is when we might have unsafe IO. Handling IO is something I haven't figured yet how to do.

In general , it is safe to remove all unnamed bindings. In fact we should change the datatype and remove that constructor.
Malfunction does support them, but we do not need them.

**Comment by fredefox** [comment]
Ah! I see. In that case we should slate it for removal, and we can ignore the error call.

**Comment by xekoukou** [comment]
@fredefox I would describe the changes as : 
``` Update to support Agda's latest commit "fcf866c94fa6e1824d8c2a3cb59d7ac2cc0b21f9" and removal of unnecessary top-level Bindings.```

**Comment by xekoukou** [comment]
I am closing this pull request since I am already many commits ahead in my other branches and I won't be able to merge any changes you might make here.

**Pull request closed without merging**
